"""Tests for the verbal-autopsy temporal-ordering pipeline.

Fake LangChain runnables stand in for the LLM chains, so ``build_temporal_order``
is exercised end-to-end (statement DAG -> entity extraction -> layered timeline
-> structured ``VATimeline``) without a model, network, or Bedrock token - safe
to run on CI.

An optional live integration test hits the real inference service; it is
skipped unless ``BEDROCK_BEARER_TOKEN`` is set in the environment.
"""
import os

import pytest
from langchain_core.runnables import RunnableLambda

from coda.grounding.temporal_ordering.llm_processors import (
    build_envent_extractor_chain,
    build_llm,
    build_temporal_order,
    build_temporal_statements_ordering_chain,
)
from coda.grounding.temporal_ordering.modeling import (
    ClinicalEvent,
    TimeBreakCategory,
    VATimeline,
)

# A fictional verbal autopsy narrative generated by Claude Opus 4.8.
NARRATIVE = """\
My daughter was healthy until two weeks before she died. She got watery diarrhea, \
several times a day, no blood in it. A few days later she started vomiting and \
couldn't keep food or water down. The night before she died she had a seizure. \
She died at home in the early morning."""

# Canned partial-order graph the ordering chain would return for NARRATIVE.
GRAPH = {
    "nodes": [
        {
            "index": 1,
            "statement": "She got watery diarrhea.",
            "time_break_marker": "two weeks before she died",
            "time_break_category": "proximity_death",
        },
        {
            "index": 2,
            "statement": "She started vomiting.",
            "time_break_marker": "A few days later",
            "time_break_category": "relative_time",
        },
        {
            "index": 3,
            "statement": "She had a seizure.",
            "time_break_marker": "The night before she died",
            "time_break_category": "proximity_death",
        },
        {
            "index": 4,
            "statement": "She died at home.",
            "time_break_marker": None,
            "time_break_category": None,
        },
    ],
    "edges": [
        {"from": 1, "to": 2},
        {"from": 2, "to": 3},
        {"from": 3, "to": 4},
    ],
}

# Canned entity extraction the events chain would return for GRAPH.
ENTITIES = {
    "statement_entities": [
        {"statement_index": 1, "entities": [{"type": "symptom", "text": "watery diarrhea"}]},
        {"statement_index": 2, "entities": [{"type": "symptom", "text": "vomiting"}]},
        {"statement_index": 3, "entities": [{"type": "health_event", "text": "seizure"}]},
        {"statement_index": 4, "entities": [{"type": "health_event", "text": "died"}]},
    ],
}


@pytest.fixture
def ordering_chain():
    """Fake ordering chain that returns the canned statement DAG."""
    return RunnableLambda(lambda _: GRAPH)


@pytest.fixture
def events_chain():
    """Fake events chain that returns the canned entity extraction."""
    return RunnableLambda(lambda _: ENTITIES)


def test_build_temporal_order_returns_va_timeline(ordering_chain, events_chain):
    result = build_temporal_order(NARRATIVE, ordering_chain, events_chain)

    assert isinstance(result, VATimeline)
    # va_narrative is only echoed back when explicitly requested.
    assert result.va_narrative is None


def test_build_temporal_order_includes_narrative_when_requested(ordering_chain, events_chain):
    result = build_temporal_order(
        NARRATIVE, ordering_chain, events_chain, include_va_in_output=True
    )

    assert result.va_narrative == NARRATIVE


def test_statement_graph_preserves_nodes_and_time_breaks(ordering_chain, events_chain):
    result = build_temporal_order(NARRATIVE, ordering_chain, events_chain)
    graph = result.statement_graph

    assert [n.index for n in graph.nodes] == [1, 2, 3, 4]
    assert graph.nodes[0].time_break_category is TimeBreakCategory.PROXIMITY_DEATH
    assert graph.nodes[1].time_break_category is TimeBreakCategory.RELATIVE_TIME
    # A node with no explicit temporal expression carries no category/marker.
    assert graph.nodes[3].time_break_category is None
    assert graph.nodes[3].time_break_marker is None
    assert [(e.source, e.dest) for e in graph.edges] == [(1, 2), (2, 3), (3, 4)]


def test_event_timeline_orders_events_chronologically(ordering_chain, events_chain):
    result = build_temporal_order(NARRATIVE, ordering_chain, events_chain)
    components = result.event_timeline.components

    # The DAG is a single chain, so there is one connected component.
    assert len(components) == 1

    # Flatten the layered events for this component in chronological order.
    events = [event for layer in components[0].layers for event in layer.events]
    texts = [e.text for e in events]

    assert texts == ["watery diarrhea", "vomiting", "seizure", "died"]
    # Death lands in its natural chronological position: last in the chain.
    assert events[-1].type_ is ClinicalEvent.HEALTH_EVENT
    assert events[-1].text == "died"


@pytest.mark.skipif(
    not os.getenv("BEDROCK_BEARER_TOKEN"),
    reason="requires BEDROCK_BEARER_TOKEN and network access to the inference service",
)
def test_build_temporal_order_live():
    """End-to-end run against the real inference service."""
    base_url = "https://bedrock-mantle.us-east-1.api.aws/v1"
    model = "qwen.qwen3-next-80b-a3b-instruct"

    llm = build_llm(
        model=model, base_url=base_url, bearer_token=os.environ["BEDROCK_BEARER_TOKEN"]
    )
    stmt_chain = build_temporal_statements_ordering_chain(llm)
    entity_chain = build_envent_extractor_chain(llm)

    result = build_temporal_order(
        NARRATIVE, stmt_chain, entity_chain, include_va_in_output=True
    )

    assert isinstance(result, VATimeline)
    assert result.va_narrative == NARRATIVE
    assert result.statement_graph.nodes
